
services:
  php:
    container_name: setup-php
    build:
      context: ./docker/php
      dockerfile: Dockerfile
    restart: unless-stopped
    tty: true
    volumes:
      - ./:/var/www
      - ./docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
     
    networks:
      - network-cassinopix

  nginx:
    container_name: setup-nginx
    build:
      context: ./docker/nginx
      dockerfile: Dockerfile
    restart: unless-stopped
    tty: true
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - ./:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - network-cassinopix

  mysql:
    container_name: setup-mysql
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    tty: true
    volumes:
      - data-cassinopix:/var/lib/mysql/
      - ./docker/mysql/my.cnf:/etc/mysql/my.cnf
      - ./cassinopix.sql:/var/db/cassinopix.sql
    networks:
      - network-cassinopix
    ports:
      - '3306:3306'
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}


  phpmyadmin:
    container_name: setup-phpmyadmin
    image: phpmyadmin:5.2
    restart: always
    ports:
      - '8888:80'
    networks:
      - network-cassinopix
    environment:
      PMA_HOST: setup-mysql
    depends_on:
      - mysql

  redis:
    container_name: setup-redis
    image: redis:latest
    build:
      context: ./docker/redis
      dockerfile: Dockerfile
    ports:
      - '6379:6379'
    networks:
      - network-cassinopix

networks:
  network-cassinopix:
    driver: bridge


volumes:
  data-cassinopix:
    driver: local
